<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CashFlow.ConsolidationProcessor.Repository\CashFlow.ConsolidationProcessor.Repository.csproj" />
    <ProjectReference Include="..\CashFlow.ConsolidationProcessor.Domain\CashFlow.ConsolidationProcessor.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
