<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CashFlow.ConsolidationQuery.Core\CashFlow.ConsolidationQuery.Core.csproj" />
    <ProjectReference Include="..\CashFlow.ConsolidationQuery.Repository\CashFlow.ConsolidationQuery.Repository.csproj" />
    <ProjectReference Include="..\..\..\CashFlow.ServiceDefaults\CashFlow.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
